import type { IProject } from '~/interfaces/project';

export const projects: IProject[] = [
  {
    title: 'HealthCare',
    description: 'Frontend Development',
    slug: '/project/zable',
    pages: [
      {
        img: '/projects/03/1.png',
        url: 'https://zable.com.au/',
      },
      {
        img: '/projects/03/2.png',
        url: 'https://zable.com.au/find-care/gastroenterologist',
      },
      {
        img: '/projects/03/3.png',
        url: 'https://zable.com.au/booking?lat=-28.0099412&lng=153.3910447&location=Benowa+QLD+4217&category=Gastroenterologist',
      },
      {
        img: '/projects/03/4.png',
        url: 'https://zable.com.au/booking?lat=-28.0099412&lng=153.3910447&location=Benowa+QLD+4217&category=Gastroenterologist',
      },
      {
        img: '/projects/03/5.png',
        url: 'https://zable.com.au/for-surgeons',
      },
      {
        img: '/projects/03/6.png',
        url: 'https://zable.com.au/payment',
      },
      {
        img: '/projects/03/7.png',
        url: 'https://zable.com.au/profile/animesh-mishra',
      },
    ],
    about: 'The project description will be added soon 👨‍💻',
    stack: [
      'Next.js',
      'TypeScript',
      'Zustand',
      'GraphQL',
      'Styled-components',
      'TailwindCss',
      'Zod',
      'Vite',
      'react-markdown',
      'remark-gfm',
      'rehype-raw',
      'react-hook-form',
      'react-gtm-module',
      'axios',
      'Google Tag Manager',
      'Google Analytics',
      'Chargebee',
      'Jotform',
      'Webflow',
      'storybook',
      'husky',
      'nx',
      '@tanstack/react-query',
      'valtio',
      'lodash',
      '@radix-ui',
      'react-day-picker',
      'vitest',
      'aws services',
      'Google Maps Api',
      'Node.js',
      'Zendesk',
    ],
  },
  {
    title: 'Nonstandard design example',
    description: 'Frontend Development',
    slug: '/project/go-surf',
    pages: [
      {
        img: '/projects/02/1.png',
        url: 'https://surfgulp.netlify.app/',
      },
      {
        img: '/projects/02/2.png',
        url: 'https://surfgulp.netlify.app/',
      },
      {
        img: '/projects/02/3.png',
        url: 'https://surfgulp.netlify.app/',
      },
      {
        img: '/projects/02/4.png',
        url: 'https://surfgulp.netlify.app/',
      },
    ],
    about: 'The project description will be added soon 👨‍💻',
    stack: [
      'HTML',
      'SCSS',
      'JavaScript',
      'jQuery',
      'gulp',
      'netlify',
      'mobile & responsive design',
    ],
  },
  {
    title: 'E-commerce',
    description: 'Frontend Development',
    slug: '/project/sport-shop',
    pages: [
      {
        img: '/projects/01/1.png',
        url: 'https://gofit-shopgulp.netlify.app/',
      },
      {
        img: '/projects/01/2.png',
        url: 'https://gofit-shopgulp.netlify.app/product.html',
      },
      {
        img: '/projects/01/3.png',
        url: 'https://gofit-shopgulp.netlify.app/catalog.html',
      },
      {
        img: '/projects/01/4.png',
        url: 'https://gofit-shopgulp.netlify.app/cart.html',
      },
    ],
    about: 'The project description will be added soon 👨‍💻',
    stack: [
      'HTML',
      'SCSS',
      'JavaScript',
      'jQuery',
      'gulp',
      'netlify',
      'Responsive Design',
      'Cross-Browser Compatibility',
    ],
  },
  {
    title: 'Portfolio',
    description: 'Fullstack Development',
    slug: '/project/portfolio',
    git: 'https://github.com/IuriiKyrylovskyi/Portfolio_nuxt',
    pages: [
      {
        img: '/projects/04/01.png',
        url: 'https://kyrylovskyi-yurii.netlify.app/about',
      },
      {
        img: '/projects/04/02.png',
        url: 'https://kyrylovskyi-yurii.netlify.app/portfolio',
      },
      {
        img: '/projects/04/03.png',
        url: 'https://kyrylovskyi-yurii.netlify.app/skills',
      },
      {
        img: '/projects/04/04.png',
        url: 'https://kyrylovskyi-yurii.netlify.app/contact-me',
      },
      {
        img: '/projects/04/05.png',
        url: 'https://kyrylovskyi-yurii.netlify.app/project/zable',
      },
      {
        img: '/projects/04/06.png',
        url: 'https://kyrylovskyi-yurii.netlify.app/help',
      },
      {
        img: '/projects/04/07.png',
        url: 'https://kyrylovskyi-yurii.netlify.app',
      },
    ],
    about: 'The project description will be added soon 👨‍💻',
    stack: [
      'Nuxt 3',
      'Node',
      'TypeScript',
      'TailwindCss',
      'Server componets',
      'Vite',
      'Nodemailer',
      'Motion',
      'Swiper',
      'SEO',
      'Buy me a coffee',
      'Netlify',
      'Git',
      'Github',
      'Responsive Design',
      'Cross-Browser Compatibility',
    ],
  },
  {
    title: 'HealthCare',
    description: 'Fullstack Development',
    slug: '/project/nexamind',
    pages: [
      {
        img: '/projects/05/01.png',
        url: 'https://mental-health-app-six.vercel.app/ua',
      },
      {
        img: '/projects/05/02.png',
        url: 'https://mental-health-app-six.vercel.app/ua/psychotherapists',
      },
      {
        img: '/projects/05/03.png',
        url: 'https://mental-health-app-six.vercel.app/ua/profile/oksana-pedchenko',
      },
      {
        img: '/projects/05/04.png',
        url: 'https://mental-health-app-six.vercel.app/ua/profile/oksana-pedchenko',
      },
      {
        img: '/projects/05/05.png',
        url: 'https://mental-health-app-six.vercel.app/ua/profile/oksana-pedchenko',
      },
    ],
    about: 'The project description will be added soon 👨‍💻',
    stack: [
      'Next.js',
      'TypeScript',
      'Node',
      'Zustand',
      'Styled components',
      'Server componets',
      'Vite',
      'Nodemailer',
      'Motion',
      'Swiper',
      'Stripe',
      'Multy currency',
      'GPay',
      'ApplePay',
      'i18',
      'SEO',
      'Rest API',
      'axios',
      'Auth',
      'Git',
      'Github',
      'AWS services',
      'Responsive Design',
      'Cross-Browser Compatibility',
    ],
  },
  {
    title: 'NFT project',
    description: 'Frontend Development',
    slug: '/project/cyber-arena',
    pages: [
      {
        img: '/projects/06/01.png',
        url: 'https://cyber-arena.vercel.app/',
      },
      {
        img: '/projects/06/02.png',
        url: 'https://cyber-arena.vercel.app/',
      },
      {
        img: '/projects/06/03.png',
        url: 'https://cyber-arena.vercel.app/',
      },
      {
        img: '/projects/06/04.png',
        url: 'https://cyber-arena.vercel.app/',
      },
      {
        img: '/projects/06/05.png',
        url: 'https://cyber-arena.vercel.app/nft',
      },
    ],
    about: 'The project description will be added soon 👨‍💻',
    stack: [
      'Next.js',
      'TypeScript',
      'Node',
      'Styled components',
      'Vite',
      'Motion',
      'Swiper',
      'Nft wallets',
      'SEO',
      'Rest API',
      'axios',
      'Git',
      'Github',
      'Vercel',
      'AWS services',
      'Non standart design',
      'Responsive Design',
      'Cross-Browser Compatibility',
    ],
  },
  {
    title: 'TV Bland',
    description: 'Frontend Development',
    slug: '/project/tv-bland',
    git: 'https://github.com/IuriiKyrylovskyi/nada-tv-test',
    pages: [
      {
        img: '/projects/07/01.png',
        url: 'https://nada-tv-test.vercel.app/',
      },
      {
        img: '/projects/07/02.png',
        url: 'https://nada-tv-test.vercel.app/shows/8566',
      },
      {
        img: '/projects/07/03.png',
        url: 'https://nada-tv-test.vercel.app/shows/15308',
      },
    ],
    about: 'The project description will be added soon 👨‍💻',
    stack: [
      'Next.js',
      'TypeScript',
      'Node',
      'Styled components',
      'Vite',
      'Real api',
      'Lazy image loader',
      'Pagination',
      'Rest API',
      'axios',
      'Git',
      'Github',
      'Vercel',
      'e2e',
      'Playwright',
      'unit tests',
      'Jest',
      'Responsive Design',
      'Cross-Browser Compatibility',
    ],
  },
];
